export const featuresPorPlano = {
  gratis: {
    crmComercial: false,
    crmBasico: false,
    crmInteligente: false,
    crmWhatsapp: false,
    crmFollowUp: false,
  },
  basico: {
    crmComercial: true,
    crmBasico: true,
    crmInteligente: false,
    crmWhatsapp: false,
    crmFollowUp: false,
  },
  profissional: {
    crmComercial: true,
    crmBasico: true,
    crmInteligente: true,
    crmWhatsapp: true,
    crmFollowUp: false,
  },
  premium: {
    crmComercial: true,
    crmBasico: true,
    crmInteligente: true,
    crmWhatsapp: true,
    crmFollowUp: true,
  },
};

export const PLANOS = {
  gratis: {
    nome: "Grátis",
    preco: 0,
    empresas: 1,
    vendasMes: 50,
    dre: false,
    pdfProfissional: false,
    personalizacao: false,
    relatoriosAvancados: false,
    ...featuresPorPlano.gratis,
    recursos: [
      "1 empresa",
      "Até 50 vendas por mês",
      "Insumos, produtos e produção básica",
      "Estoque e financeiro simples",
    ],
    limitacoes: [
      "Sem DRE",
      "Sem PDF profissional",
      "Sem personalização visual",
      "Sem CRM Comercial",
    ],
  },
  basico: {
    nome: "Básico",
    preco: 1,
    empresas: 1,
    vendasMes: null,
    dre: false,
    pdfProfissional: false,
    personalizacao: false,
    relatoriosAvancados: false,
    ...featuresPorPlano.basico,
    recursos: [
      "1 empresa",
      "Vendas ilimitadas",
      "Produção completa",
      "Estoque com alerta mínimo",
      "Financeiro completo",
      "Relatórios simples",
      "CRM básico de clientes",
      "Histórico de compras por cliente",
    ],
    limitacoes: [
      "Sem DRE avançado",
      "Sem PDF profissional",
      "Sem personalização visual",
      "Sem recompra inteligente",
      "Sem follow-up comercial",
    ],
  },
  profissional: {
    nome: "Profissional",
    preco: 1,
    empresas: 3,
    vendasMes: null,
    dre: true,
    pdfProfissional: true,
    personalizacao: true,
    relatoriosAvancados: true,
    ...featuresPorPlano.profissional,
    recursos: [
      "Até 3 empresas",
      "Tudo do Básico",
      "DRE completo",
      "Relatórios completos",
      "PDF profissional com logo",
      "Personalização com cores",
      "CRM inteligente",
      "Recompra prevista",
      "Status de clientes prontos para comprar",
      "Indicadores da carteira",
      "Suporte básico",
    ],
    limitacoes: [],
  },
  premium: {
    nome: "Premium",
    preco: 149,
    empresas: null,
    vendasMes: null,
    dre: true,
    pdfProfissional: true,
    personalizacao: true,
    relatoriosAvancados: true,
    ...featuresPorPlano.premium,
    recursos: [
      "Empresas ilimitadas",
      "Tudo liberado",
      "Nome do sistema personalizado",
      "Identidade visual completa",
      "Relatórios avançados",
      "CRM completo",
      "WhatsApp para clientes",
      "Follow-up comercial",
      "Contatos de hoje",
      "Prioridade no suporte",
    ],
    limitacoes: [],
  },
};

export const assinaturaGratisPadrao = {
  plano: "gratis",
  status: "active",
  vencimento: null,
  ativadoManual: true,
  formaPagamento: "manual",
  valorPago: 0,
  observacao: "",
};

export const getPlanoConfig = (plano = "gratis") => {
  return PLANOS[plano] || PLANOS.gratis;
};
